version: "2"

services:
    backend:
        build:
            context: ./express-backend
            dockerfile: Dokerfile
        ports:
            - "3000:3000"
        container_name: back-end
        restart: always
