version: "2"

services:
    frontend:
        build: "tony-and-c-app/"
        ports:
            - "4200:4200"
        container_name: front-container_name
        restart: always

    #backend:
    #    build: "express-backend/"
    #    ports:
    #        - "3000:3000"
    #    container_name: back-container_name
    #    restart: always
